[package]
name = "netproto"
version = "0.1.0"
authors = ["Michael Baumgarten <mb2732@rit.edu>"]
edition = "2018"

description = "library used for mapping network packets into usable structs"
license = "MIT"

[dependencies]
